[build]
command = "SHARP_FORCE_INSTALL=true pnpm install && pnpm rebuild sharp --force && pnpm run build"
publish = "dist"

[build.environment]
SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
SHARP_INSTALL_FORCE = "true"
